site_name: Pelf - Pipelines for seeking grants and partnerships
repo_url: https://github.com/artfulrobot/pelf
site_description: 'Pelf - pipeline management of funding prospects and contracts'
site_author: 'Rich Lott / Artful Robot'
theme:
  name:
    material

nav:
- Home: index.md
- Tutorial: tutorial/index.md
- How To:
  - About: howto/index.md
  - Install: howto/install.md
- Discussion: discussion/index.md
- Reference:
    - 'About' : reference/index.md
    - 'Technical': reference/technical.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - pymdownx.highlight:
      guess_lang: False
  - toc:
      permalink: True
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
