-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--


-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_pelf_funds_allocation`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_pelf_funds_allocation
-- *
-- * Describes financial year and project breakdown for a Pelf Venture
-- *
-- *******************************************************/
CREATE TABLE `civicrm_pelf_funds_allocation` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique PelfFundsAllocation ID',
     `case_id` int unsigned    COMMENT 'FK to Case',
     `amount` decimal(20,2)    COMMENT 'Amount in local currency',
     `project` int unsigned    COMMENT 'OptionValue for project',
     `fy_start` date    COMMENT 'Date of start of the financial year to which this ammount is allocated.' 
,
        PRIMARY KEY (`id`)
 
 
,          CONSTRAINT FK_civicrm_pelf_funds_allocation_case_id FOREIGN KEY (`case_id`) REFERENCES `civicrm_case`(`id`) ON DELETE CASCADE  
)    ;

 
